### ISSUE TITLE
Can not resolve reference Xamarin.Android.Support.Loader

### ISSUE THREAD

**Issue by denzerd** [baskren/Forms9Patch#13]
Hi,

I tried to user your lib in my project, it worked like a charm under iOS. :)
Unfortunately under Android I struggle to get it running.

When I try to run the project I get the error:

> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(2,2): Error XA2002: Can not resolve reference: `Xamarin.Android.Support.Loader`, referenced by `Forms9Patch.Droid`. Please add a NuGet package or assembly reference for `Xamarin.Android.Support.Loader`, or remove the reference to `Forms9Patch.Droid`. (XA2002) (F62App.Android)

It is a bit strange to get this error as Xamarin.Android.Support.Loader is not mentioned as a dependency for your library.
However, even if I add the Xamarin.Android.Support.Loader package to my Android projects packages I get this error. 
Any advice?

I'm using Visual Studio Community for Mac 8.1.2 (build 2) and Xamarin.Forms 4.1.0.555618 and the version 1.8.0 of Forms9Patch.
I'm trying to run it on a x86 Emulator.

Let me know if you need any other information.

Thank you!

**Comment by denzerd** [comment]
Small addition, I just tried with version 1.7.0 and the error is gone.
So it seems to be a regression for 1.8.0. 
It is an acceptable workaround for me for the moment as I don't necessarily need the newest but of course I would prefer to have the most up to date one :)

**Comment by gogolon** [comment]
I have been facing this issue. too Downgrading to 1.7 works, but I would rather use the newest version.

**Comment by baskren** [comment]
Looking at the dependencies used in the Forms9PatchDemo.Android vs. those in Xamarin.Forms 4.0.0.49...m, it appears that there is one missing dependency:

```
                <dependency id="Xamarin.Android.Support.Core.Utils" version="28.0.0.1" />
```

For the sake of being cautious, I am adding that dependency to the Forms9Patch.NuSpec as well as the other found in Xamarin.Forms 4.0.0.49.  I'll try to have an update out later today.

**Comment by baskren** [comment]
version 1.8.0.1 has been released

**Comment by baskren** [comment]
FWIW, I'm also going to reference the following issue thread from Rg.Plugins.Popup, since Forms9Patch uses it and the solution could be applicable to others.

https://github.com/rotorgames/Rg.Plugins.Popup/issues/233

**Comment by baskren** [comment]
Likewise, here is the same fix applied to a different instance of this issue: https://forums.xamarin.com/discussion/109615/could-not-load-assembly-xamarin-android-support-fragment-version-1-0-0-0

**Comment by baskren** [comment]
Alternatively: https://forums.xamarin.com/discussion/149377/error-updating-xamarin-andoird-nuget-packages

**Comment by nrooban** [comment]
Hi @baskren Thank you for the awesome plugin.  I am getting 'Can not resolve reference Xamarin.Android.Support.Loader' even with Forms9Patch 2.2.4 but iOS is working fine. If I downgraded to 1.8.1 still the same and the iOS project also breaks. 

Kindly check on this please.

**Comment by baskren** [comment]
@nrooban 

Please try the following:

1. (Optional) Try out the [demo project](https://github.com/baskren/Forms9Patch/tree/master/Demo/UsingForms9PatchNuGet).  Does it do the same thing?
2. (Optional) If the demo project works, take a closer look at the getting [started guide](https://baskren.github.io/Forms9Patch/guides/GettingStartedWindows.html) as you've likely not configured your project correctly.  My guess is that your Android NuGet packages are not quite right and suggest verifying that all the versions of them are the same across all of your projects (including inside of Forms9Patch).  
3.  If you don't get anywhere with the above, please share with me a small demo project that produces the error you're seeing.  If I can't reproduce it, I'm not going to be able to find the root cause for you.
