### ISSUE TITLE
Issue #12 Still occurring after fix

### ISSUE THREAD

**Issue by KCarterSr** [baskren/Forms9Patch#14]
Specifically.

When HorizontalOptions or VerticalOptions on the label is set to CENTER,  the crash occurs.

Thanks

**Comment by baskren** [comment]
@KCarterSr 

Given the information provided, (crash report and screen shots), there isn't enough information available for me to replicate.  Without being to replicate, I am not able to find the root cause and fix the issue.  

I would like to fix this issue.  If you can provide a sample project that demonstrates this issue, I should be able to address this.

**Comment by KCarterSr** [comment]
I'll be on vacation until Aug. I can't make you a solution but when I get some free time I'll type out a written 
 explanation of how you can replicate it.

**Comment by baskren** [comment]
Not enough information to pursue.
