### ISSUE TITLE
 Issue with Forms9Patch.iOS on Target Device

### ISSUE THREAD

**Issue by toyins46** [baskren/Forms9Patch#17]
When I tried compiling my app using the Simulator there isn't any problems. However, when I tried pointing the app to an actual device (iPhone 7 plus),
I get this error message.
Severity Code Description Project File Line Suppression State
Error Can't resolve the reference 'CoreGraphics.CGRect UIKit.NSLayoutManager::GetLineFragmentRect(System.nuint,Foundation.NSRange&)',
referenced from the method 'System.UInt32 Forms9Patch.iOS.UITextViewExtensions::NumberOfLines(UIKit.UITextView)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'. MyApp.iOS.
I have downgraded the Forms9Patch package, using older version 1.8.0 that did not work.
I'm using the latest Forms9Patch package 1.8.0.2.

**Comment by baskren** [comment]
- What version of iOS is on your device?  
- What version of iOS are you targeting in your build (via info.plist)?
- What version of VisualStudio are you using (Mac or PC)?  
   - If Mac, do you have the BruteClean or DeepClean extension installed?  Once installed (you may have to restart Visual Studio), click Build / Delete /obj /bin Directories and then restart Visual Studio. Now try your build again. 
   - If Windows, do you have the CleanBinAndObj extension install?  Once installed (you may have to restart Visual Studio), click Build / Clean Bin and Obj and then restart Visual Studio. Now try your build again.  
- Please provide me a complete stack trace.
- For faster response and less iterations (with all the lag time between iterations), please provide a link to a Git repo (GitHub, BitBucket, etc) that contains a small demo project that produces the issue.  By the way, this is the only way to guarantee a fix, let along a fast fix, to an issue.

**Comment by baskren** [comment]
I'm really stumped now.  `UIKit.NSLayoutManager::GetLineFragmentRect` [has been around since iOS 7](https://developer.apple.com/documentation/uikit/nslayoutmanager/1403140-linefragmentrect) so there doesn't appear to be a legitimate reason why Forms9Patch would set you up to gett a **Can't resolve the reference** error.  

Just out of curiosity, what are your linker settings?  Perhaps the linker is missing that `GetLineFragmentRect` is needed and removing it?  It might be worth some time to do a side by side (Simulator vs. iPhone) comparison of all your project settings.

**Comment by toyins46** [comment]
I have resolved it by changing the Link Behavior in iOS to Don't Link.
