### ISSUE TITLE
Linker Error

### ISSUE THREAD

**Issue by mabdollahiasl** [baskren/Forms9Patch#26]
I have a problem with building after update to version 1.8.1, I get the flowing error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error		The "LinkAssemblies" task failed unexpectedly.
> Mono.Linker.MarkException: Error processing method: 'System.Int32 Forms9Patch.Droid.TextControlState::GetHashCode()' in assembly: 'Forms9Patch.Droid.dll' ---> Mono.Cecil.ResolutionException: Failed to resolve System.Int32 System.HashCode::Combine(!!0)
>    at Mono.Linker.Steps.MarkStep.HandleUnresolvedMethod(MethodReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkMethod(MethodReference reference)
>    at Mono.Linker.Steps.MarkStep.MarkInstruction(Instruction instruction)
>    at Mono.Linker.Steps.MarkStep.MarkMethodBody(MethodBody body)
>    at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method)
>    at Mono.Linker.Steps.MarkStep.ProcessQueue()
>    --- End of inner exception stack trace ---
>    at Mono.Linker.Steps.MarkStep.ProcessQueue()
>    at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
>    at Mono.Linker.Steps.MarkStep.Process()
>    at MonoDroid.Tuner.MonoDroidMarkStep.Process(LinkContext context)
>    at Mono.Linker.Pipeline.Process(LinkContext context)
>    at MonoDroid.Tuner.Linker.Process(LinkerOptions options, ILogger logger, LinkContext& context)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute(DirectoryAssemblyResolver res)
>    at Xamarin.Android.Tasks.LinkAssemblies.Execute()
>    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
>    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	Healx.Android

**Comment by baskren** [comment]
@mabdollahiasl -  Can you send me a small sample project that demonstrates this issue?  Without being able to replicate it, there is no hope of being able to find the root cause and fix.

That being said, have you tried [Googling it](https://www.google.com/search?q=Mono.Linker.MarkException%3A+Error+processing+method%3A+Mono.Linker.MarkException%3A+Error+processing+method%3A&oq=Mono.Linker.MarkException%3A+Error+processing+method%3A+Mono.Linker.MarkException%3A+Error+processing+method%3A&aqs=chrome..69i57j0.16302j0j7&sourceid=chrome&ie=UTF-8)?  Some of the top hits are suggesting project configuration issues (which means you won't be able to replicate this issue in a demo project).

**Comment by mabdollahiasl** [comment]
thank you for your response...
I use vs 2017 latest update.
my app build and run on debug mode without any problems.
I make an empty project and add Forms9Patch but I get the same error on release mode.
I attach the sample.
[App16.zip](https://github.com/baskren/Forms9Patch/files/3636061/App16.zip)

**Comment by mabdollahiasl** [comment]
I Update to vs 2019 and problem solved.

**Comment by baskren** [comment]
@mabdollahiasl -  glad to hear updating helped.  VS2019 may have better logic to address the kind project configuration issues that seem to cause issues like this.
