### ISSUE TITLE
TapGestureRecognizer not working in FlyoutPopup Android

### ISSUE THREAD

**Issue by Matmork** [baskren/Forms9Patch#40]
TapGestureRecognizer does not trigger in FlyoutPopup on Android. Works on UWP and iOS. 

Example with a Label. Should close the popup when clicked:
```
public ICommand FlyoutPopupCommand => new Command(() =>
        {
            var popup = new FlyoutPopup();

            var content = new Xamarin.Forms.Label
            {
                Text = "Close",
                Padding = 20,
                BackgroundColor = Color.Gray,
                HorizontalOptions = LayoutOptions.Center,
                VerticalOptions = LayoutOptions.Center,
                GestureRecognizers = { new TapGestureRecognizer
                {
                    Command = new Command(() => popup.IsVisible = false)
                }}
            };

            popup.Content = content;
            popup.IsVisible = true;
});
```

Forms9Patch: 2.1.3
Xamarin Forms: 4.3.0.991250

[TapGestureRecognizer_FlyoutPopup.zip](https://github.com/baskren/Forms9Patch/files/4052828/TapGestureRecognizer_FlyoutPopup.zip)

**Comment by baskren** [comment]
@Matmork 

I have a work around for you (if you're impatient, then skip to **Work Around**) but first, some background.

## Background 

You have just poked me in the eye!  What a mean is that I know of 5 ways to handle gestures in Xamarin.Forms (I'm sure there are more):
 - Xamarin.Forms Gesture Recognizers
 - FormsGestures (a part of Forms9Patch)
 - Mr. Gestures (what a great project!)
 - SkiaSharp Gestures
 - Write your own

The bad news is that, because of the way they are written, they all don't play well with each other - especially Xamarin.Forms Gesture Recognizers!  When I wrote FormsGestures, I wanted the ability to handle a few gestures (like up, down, double tap, LongPressing, LongPressed) that Xamarin.Forms didn't.  Since then, on a couple of projects that I've done, I found that Xamarin.Forms gestures also don't work consistently across platforms in a few edge cases.  Because of these reasons, I've reluctantly continued to maintain FormsGestures.

FormsGestures is the bases for the Gestures in Forms9Patch - including the gestures required to swipe cancel a FlyoutPopup.  Because this gesture is in the same visual tree as your GestureRecognizer, they bump into each other during Android's gesture initiation process.  This is something that I put WAY TOO MUCH effort in to mitigate but I never got to the point where it was perfect.

Don't get me wrong - there are lots of things I like about Xamarin.Forms Gesture Recognizer.  Unfortunately it's just not as comprehensive enough for my needs and, as such, I find myself needing to be sure I'm not mixing it with other gesture recognizers on a regular basis.  Using FormsGestures in the FlyoutPopup was an instance of this.

## Work Around

There are likely a bunch of work arounds - all of which involve not using Xamarin.Forms Gesture Recognizer.  Below is a modified version of your code that I've added to the Forms9Patch demo:

https://github.com/baskren/Forms9Patch/blob/47da890429af63a4e85993f6cf75a94a947cf11c/Demo/Forms9PatchDemo.Common/UserPages/FlyoutGestureFail/FlyoutGestureFail.cs#L28-L65

Also note that I've added some comments to the code about managing the disposal of `FlyoutPopup` and `FormsGesture.Listener` by wrapping their scope in a `using` block.  If you have any questions about that, just let me know.

**Comment by Matmork** [comment]
Thank you for the detailed explanation and work around!
I found that just an ordinary xamarin.forms.button also works.

Ill be sure to wrap my popups in a using block, thanks!
closing this issue.
