### ISSUE TITLE
Multiple TargetedToasts at the same time

### ISSUE THREAD

**Issue by sqrg** [baskren/Forms9Patch#41]
Is it possible to have multiple TargetedToasts showing at the same time? Currently, they all show, but only the last one created is not darkened.

![image](https://user-images.githubusercontent.com/4741366/73182727-50ce8400-40f8-11ea-9ad3-d94bbb85c078.png)

EDIT: Or an option to not darken anything would be useful as well

**Comment by baskren** [comment]
Yes.  Set the popup’s PageOverlayColor property to something almost transparent- but not completely transparent.  Why?  Because if the PageOverlayColor is completely transparent then the PageOverlay will ignore gestures (at least on some platforms) and you won’t be able to tap the background to cancel the popup.

**Comment by sqrg** [comment]
Thanks. That worked OK
