### ISSUE TITLE
[Xamarin.forms] [UWP] 2.2.4 version not working 

### ISSUE THREAD

**Issue by jitendrajadav** [baskren/Forms9Patch#43]
Xamarin forms uwp 10 version 2.2.4 is not working I am getting error like below 
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "C:\Users\jdj1\.nuget\packages\forms9patch\2.2.4\lib\uap10.0\FormsGestures.UWP\Microsoft.UI.Xaml\DensityStyles\Compact.xaml" because it was not found.	KegID.UWP	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4643	
`
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "C:\Users\jdj1\.nuget\packages\forms9patch\2.2.4\lib\uap10.0\FormsGestures.UWP\Microsoft.UI.Xaml\DensityStyles\Compact.xaml" because it was not found.	KegID.UWP	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4643	
`
`Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "C:\Users\jdj1\.nuget\packages\forms9patch\2.2.4\lib\uap10.0\Forms9Patch.UWP\Forms9Patch.UWP.xr.xml" because it was not found.	KegID.UWP	C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets	4643	
`

[Sample code is here](https://github.com/jitendrajadav/forms9UWP.git)

Version update

Microsoft Visual Studio Professional 2019 Preview
Version 16.5.0 Preview 2.0
VisualStudio.16.Preview/16.5.0-pre.2.0+29721.120
Microsoft .NET Framework
Version 4.8.03752

Installed Version: Professional

Visual C++ 2019 00435-60000-00000-AA694
Microsoft Visual C++ 2019

VisualStudio.Mac 1.0
Mac Extension for Visual Studio

Xamarin 16.5.000.400 (d16-5@4a7a7df)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer 16.5.0.391 (remotes/origin/d16-5@2aeef9a0a)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates 16.5.42 (afa79c5)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK 10.2.0.84 (d16-5/ac3f71f)
Xamarin.Android Reference Assemblies and MSBuild support.
Mono: df42020
Java.Interop: xamarin/java.interop@c0cc770
ProGuard: xamarin/proguard@905836d
SQLite: xamarin/sqlite@46204c4
Xamarin.Android Tools: xamarin/xamarin-android-tools@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK 13.14.1.17 (d308800)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.

Note : This only problem in UWP 10 android and iOS working fine

UWP 10 version info:

![image](https://user-images.githubusercontent.com/1029026/74587398-02861400-5018-11ea-88f7-82850969ac97.png)

**Comment by baskren** [comment]
@jitendrajadav - Thank you for such a PROFESSIONAL bug report.  I'm likely not going to have time today to look at this but, because you provided a demo solution - in a git repo - I will give it top priority!

**Comment by jitendrajadav** [comment]
@baskren thank you for you quick turn around really appreciate thank you again

**Comment by baskren** [comment]
@jitendrajadav 

There is just too many other things not working in demo app for me to be able to help.  Upon my first launch, the app crashed.  I then removed all references to Forms9Patch ... and the app still crashed.  Currently, the app is throwing an exception on launch that appears to be coming from the Scandit.BarcodePicker library?

![image](https://user-images.githubusercontent.com/2528888/76123570-e8ac7100-5fc6-11ea-928b-9899fccee21b.png)

If you have an application that works without Forms9Patch but doesn't with Forms9Patch, then I might be able to help.

**Comment by plexxis-htarwala** [comment]
Hi I am getting similar errors in my app with UWP. 
Error		Could not copy the file "C:\Users\Admin\.nuget\packages\forms9patch\2.2.4\lib\uap10.0\Forms9Patch.UWP\Forms9Patch.UWP.xr.xml" because it was not found.
Error		Could not copy the file "C:\Users\Admin\.nuget\packages\forms9patch\2.2.4\lib\uap10.0\FormsGestures.UWP\FormsGestures.UWP.xr.xml" because it was not found.	
Error		Could not copy the file "C:\Users\Admin\.nuget\packages\forms9patch\2.2.4\lib\uap10.0\FormsGestures.UWP\Microsoft.UI.Xaml\DensityStyles\Compact.xaml" because it was not found.	
I have a similar configuration as the original reporter of the issue.

Thanks.

**Comment by jitendrajadav** [comment]
> @jitendrajadav
> 
> There is just too many other things not working in demo app for me to be able to help. Upon my first launch, the app crashed. I then removed all references to Forms9Patch ... and the app still crashed. Currently, the app is throwing an exception on launch that appears to be coming from the Scandit.BarcodePicker library?
> 
> ![image](https://user-images.githubusercontent.com/2528888/76123570-e8ac7100-5fc6-11ea-928b-9899fccee21b.png)
> 
> If you have an application that works without Forms9Patch but doesn't with Forms9Patch, then I might be able to help.

Hi @baskren, Yes it is coming from **Scandit.BarcodePicker** 

even I had tried with same repository what I have shared with you it is working fine, probably you have to restored all the nuget packages please check 
![image](https://user-images.githubusercontent.com/1029026/76188758-f2b8b480-61fe-11ea-84ba-3a948fc9d329.png)

above attached screen short all the packages is installed 
please let me still if you wouldn't be able to run this project?


Thank you

**Comment by AlanHoiland** [comment]
Hello, 
I am also seeing the issue with 2.2.4 "could not copy file"...
Any update or workaround? Besides downgrading to 2.2.3.
Thanks,
Alan

**Comment by baskren** [comment]
@jitendrajadav 

Version 2.2.5 was published last night.  I believe it addresses the issue you have found.  Give it a try and let me know.

Also, please accept my apology for taking so darned long to fix this.  As you likely know, Forms9Patch was developed for my projects.  Originally, I tried selling licenses for it but it wasn't worth the trouble - so I open sourced it.  You can see from the commit history that I am still actively developing it **but** Forms9Patch features and issues needed for other projects I am actively developing get priority.  Unfortunately, because I almost exclusively build from source, the issue you found is one of the few that I did not see.  That is my fault and I am sorry for the trouble it has caused you.  I am not trying to make excuses - just explain where my blind spots are and how that caused me to fail to deliver a solid build for version 2.2.4.

**Comment by jitendrajadav** [comment]
@baskren Thank you very much I understand your concern it really helpful me as well to understand this problem really appreciate will update you on it again thank you:)
