### ISSUE TITLE
Status Request: Support for the Resolution Modifier @4x

### ISSUE THREAD

**Issue by NoamMani** [baskren/Forms9Patch#58]
Hi,

I saw in the documentation that support for the Resolution Modifier `@4x` is a future proof. ([Resolution Modifier Table](https://baskren.github.io/Forms9Patch/guides/ImageSource.html#resolution-modifiers))

Forms9Patch | notes | iOS analog | Android analog
-- | -- | -- | --
none | fallback image if no other is available | none (default) | none (default)
`@¾x` | low density screens (~120 dpi) | n/a | -ldpi
`@1x` | explicit medium density (~160 dpi) | none (default) | -mdpi
`@1½x` | (~240 dpi) | n/a | -hdpi
`@2x `| most common (~320) | `@2x` | -xhdpi
`@3x `| rare (~480 dpi) | `@3x` | -xxhdpi
`@4x `| **future proof** (~640 dpi) | `@4x` | -xxxhdpi

Will it be done soon? Could you please let me know about an estimated date or version that this Resolution Modifier will be?

Thanks.

**Comment by baskren** [comment]
I believe it should be working - it has been coded up since the beginning.  Are you having any problems with it?

**Comment by NoamMani** [comment]
Yes, it never takes @4x images.

**Comment by baskren** [comment]
@NoamMani -   Can you elaborate?  I ask because, when searching for the right resolution of image (@3/4x to @4x),  Forms9Patch first checks the resolution of the device.  Then it looks at each version of the image to find the one that has the closest match to the device's resolution.

https://github.com/baskren/Forms9Patch/blob/76baec5ecb3515a28e0940038e3f113ad55ae4c8/Forms9Patch/Forms9Patch/Models/ImageSource.cs#L273-L330

In order for a @4x image to be selected, the device has too be >= 560 dpi screen resolution.  See the `Min` and `Max` values in the following table:

https://github.com/baskren/Forms9Patch/blob/76baec5ecb3515a28e0940038e3f113ad55ae4c8/Forms9Patch/Forms9Patch/Models/ImageSource.cs#L350-L359

You can check your device's scale (which implicitly correlates to the resolution ... 1x = 160 dpi) by using calling `Forms9Patch.Display.Scale`.

**Comment by NoamMani** [comment]
Thanks for your response.

My device is Pixel 3XL. its screen details are: 

**Size:** 6.3 inches, 100.3 cm2 (~82.8% screen-to-body ratio)
**Resolution:** 1440 x 2960 pixels, 18.5:9 ratio (~523 ppi density)
**Scale:** 3.5

When I use forms9Patch, the image size I get is @3x, but the image is too small for the screen. 

![too small](https://user-images.githubusercontent.com/40792491/86142846-59d6dd80-bafc-11ea-8cbf-024648902bed.png)

When I add the next line: 
"new DeviceDensity { Name = "@4x",   Min=560, Max=int.MaxValue, Scale=3.5f }"
the image size I get is @4x which looks great.

![looks good](https://user-images.githubusercontent.com/40792491/86142903-6c511700-bafc-11ea-8c63-cf5eeacd1847.jpg)

**Comment by baskren** [comment]
@NoamMani 

Thank you for sharing the screen shots.  It has helped immensely in my understanding.

There are two things going on here that are note worthy:

- First, the image itself was not setup to fill the available space in its parent layout.  I'm guessing that was by design on your part?  I'm not sure how you are using this image within a layout but I would suggest considering the use of Forms9Patch.Fill: (https://baskren.github.io/Forms9Patch/guides/Image.html#fill-property) (https://baskren.github.io/Forms9Patch/api/Forms9Patch.Fill.html).  I'm guessing that you're already aware of this but didn't take this approach for a reason?

- Second, your device isn't a 4x device ... nor is it a 3x device.  It's a 3.5x device (welcome to Android).  That being said, before you made your (very smart) change to AppleDensities, 3x was chosen as the closest fit by the algorithm.  This is where Forms9Patch approach for multi-resolution support starts to show some cracks - both Android and Windows device resolutions are going to be all over the map and there just can't be a one-size-fits all approach to selecting scaled images. Hence, Forms9Patch takes the "find the nearest and then use the Image.Fill property to make it work" approach.  Not perfect but, in my testing, seemed to be pretty darned good.  I would like to get your thoughts.

**Comment by NoamMani** [comment]
Forms9Patch.Fill will not help me in this case, I don't want to stretch the image. 

I understand your algorithm, but, please explain me what is the problem with adding this line?   
"new DeviceDensity { Name = "@4x", Min=560, Max=int.MaxValue, Scale=3.5f }"

In addition, I don't have the knowledge on this topic, maybe you can help me, which drawable folder (-hdpi/-xhdpi/-xxhdpi/-xxxhdpi) devices with scale 3.5 should access? (not according to your algorithm)


Thanks
