### ISSUE TITLE
Html to PNG - Custom Font

### ISSUE THREAD

**Issue by wesoos** [baskren/Forms9Patch#70]
Hi, how would I use a custom font with the html code that I want to convert to an image?  The font is a barcode font I need...

**Comment by baskren** [comment]
Check out this guide:

https://baskren.github.io/Forms9Patch/guides/CustomFonts.html

**Comment by wesoos** [comment]
Thanks. It seems though this article relates to label, button, and other forms elements. I am using this library to convert raw html source to a png image. In the styling of the html, I'm using a custom font.  Is this possible?

Wessel Oosthuizen

________________________________

**Comment by baskren** [comment]
oh, you are living on the edge.  

Short answer:  likely.

Long Answer:

The most direct (and fool proof) approach is to embed the custom font into your html file.  Something I am not an expert in but I know it can be done - with a bit of effort (Google is your friend).  For example: https://gero3.github.io/facetype.js/.

Because the direct approach is very labor intensive, I built (but not documented) [EmbeddedHtmlViewSource](https://github.com/baskren/Forms9Patch/blob/master/Forms9Patch/Forms9Patch/Models/EmbeddedHtmlViewSource.cs) class.  I highly recommend taking a look at the source code.  I haven't adapted it to fonts, but it does handle images - so, with a little work, it could be extended to work with fonts.
