### ISSUE TITLE
[Bug] webview to png on android

### ISSUE THREAD

**Issue by bamyu** [baskren/Forms9Patch#74]
### Description
First, i'm Japanese, so i'm sorry to my not good English.
I wanna to convert webview to png,
so I downloaded demo project and try with little change such as reproduce step.
### Steps to Reproduce

1. change Source of WebViewExport.cs only like this: 
From
`webView.Source = "https://xamarin.com";`
To
`var source = new HtmlWebViewSource();`
`source.Html = "<html><head></head><body><div style='background-color: #FF0000; height: 100vw;'></div></body></html>"`
`webView.Source = source;`
2. tap topng button on android.
3. save png image

### Expected Behavior

The image and webview look the same
### Actual Behavior
The height is smaller than the displayed webview.
### Basic Information

- Version with issue:latest (Aug 26, 2020)
- Last known good version:
- IDE:VIsual Studio for Mac
- Platform Target Frameworks: 
  - iOS:  
  - Android: multiple emulators, and physical device
  - UWP:   
- Android Support Library Version: API28
- Nuget Packages:latest
- Affected Devices:

### Reproduction Link - a link to a small demo project that reproduces this issue

Your project demo.

### Workaround

I haven't find any workaround yet.

Thank you.

**Comment by baskren** [comment]
A couple of comments:

- I'm not at a point where I can test this at the moment, so take what I'm about to say with a grain of salt.
- Instead of trying the WebViewExport.cs example, could you try to accomplish the same thing using the HtmlExport.cs example?  It might not change anything but HtmlExport was written with your use-case in mind.
- I'm not 100% sure I can picture what you are seeing when you report that the png height is smaller than the displayed webview.  
   - Could you provide images of both to clearly illustrate what you are seeing?
   - There is also a `width` argument for `ToPngAsync`.  That should have influence on the rendered png size.

https://github.com/baskren/Forms9Patch/blob/fa1c848e7efe38250a2999bf974401ae578e10e2/Forms9Patch/Forms9Patch/Services/ToPngService.cs#L36
